version: 2

project_name: GOwalk

before:
  hooks:
    - go mod tidy

builds:
  - id: gowalk
    main: ./cmd/mousewalk
    binary: GOwalk

    env:
      - CGO_ENABLED=1

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

archives:
  - id: default

    formats:
      - tar.gz

    format_overrides:
      - goos: windows
        formats:
          - zip

    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  disable: false